# Brief description of config file
title = "Este Dynamic Analysis Config"

[OUTPUT]

# output-dir @type str:
#    Directory where Este will dump logs and trace data to.
output-dir = "gen/Este-out"

[ANALYSIS-SCOPE]

# binary-whitelist @type List[str]:
#    Este will analyse only binaries in this list
binary-whitelist = ["notepad.exe", "helloworld.exe", "mspaint.exe"]